OBJ_MTL_TOKEN(EndOfFile, "end of file")
OBJ_MTL_TOKEN(EndOfLine, "end of line")
OBJ_MTL_TOKEN(String, "string")
OBJ_MTL_TOKEN(Integer, "integer")
OBJ_MTL_TOKEN(Float, "float")
OBJ_MTL_TOKEN(NewMtl, "newmtl")
OBJ_MTL_TOKEN(AmbientReflectivity, "Ka")
OBJ_MTL_TOKEN(DiffuseReflectivity, "Kd")
OBJ_MTL_TOKEN(SpecularReflectivity, "Ks")
OBJ_MTL_TOKEN(Emission, "Ke")
OBJ_MTL_TOKEN(TransmissionFilter, "Tf")
OBJ_MTL_TOKEN(Illum, "illum")
OBJ_MTL_TOKEN(IllumModel, "illum_model")
OBJ_MTL_TOKEN(Dissolve, "d")
OBJ_MTL_TOKEN(SpecularExponent, "Ns")
OBJ_MTL_TOKEN(ReflectionSharpness, "sharpness")
OBJ_MTL_TOKEN(RefractionIndex, "Ni")
OBJ_MTL_TOKEN(AmbientReflectivityMap, "map_Ka")
OBJ_MTL_TOKEN(DiffuseReflectivityMap, "map_Kd")
OBJ_MTL_TOKEN(SpecularReflectivityMap, "map_Ks")
OBJ_MTL_TOKEN(SpecularExponentMap, "map_Ns")
OBJ_MTL_TOKEN(DissolveMap, "map_d")