SHADER_TOKEN(EndOfFile, "end of file")
SHADER_TOKEN(VoidType, "void")
SHADER_TOKEN(AddAssign, "+=")
SHADER_TOKEN(SubAssign, "-=")
SHADER_TOKEN(MulAssign, "*=")
SHADER_TOKEN(DivAssign, "/=")
SHADER_TOKEN(ModAssign, "%=")
SHADER_TOKEN(BitwiseAndAssign, "&=")
SHADER_TOKEN(BitwiseXorAssign, "^=")
SHADER_TOKEN(BitwiseOrAssign, "|=")
SHADER_TOKEN(LogicalOr, "||")
SHADER_TOKEN(LogicalAnd, "&&")
SHADER_TOKEN(LogicalXor, "^^")
SHADER_TOKEN(ShiftRight, ">>")
SHADER_TOKEN(ShiftLeft, "<<")
SHADER_TOKEN(Equal, "==")
SHADER_TOKEN(NotEqual, "!=")
SHADER_TOKEN(LessEqual, "<=")
SHADER_TOKEN(GreaterEqual, ">=")
SHADER_TOKEN(Increment, "++")
SHADER_TOKEN(Decrement, "--")

SHADER_TOKEN(StructQualifier, "struct qualifier")
SHADER_TOKEN(Import, "import")
SHADER_TOKEN(If, "if")
SHADER_TOKEN(Else, "else")
SHADER_TOKEN(Break, "break")
SHADER_TOKEN(Continue, "continue")
SHADER_TOKEN(Return, "return")
SHADER_TOKEN(Do, "do")
SHADER_TOKEN(For, "for")
SHADER_TOKEN(While, "while")
SHADER_TOKEN(Switch, "switch")
SHADER_TOKEN(Case, "case")
SHADER_TOKEN(Default, "default")
SHADER_TOKEN(Integer, "integer")
SHADER_TOKEN(Unsigned, "unsigned integer")
SHADER_TOKEN(Float, "float")
SHADER_TOKEN(Boolean, "boolean")
SHADER_TOKEN(StringLiteral, "string literal")
SHADER_TOKEN(VertexQualifier, "vertex qualifier")
SHADER_TOKEN(GeometryQualifier, "geometry qualifier")
SHADER_TOKEN(FragmentQualifier, "fragment qualifier")
SHADER_TOKEN(Shader, "shader")
SHADER_TOKEN(Type, "type")
SHADER_TOKEN(Function, "function")
SHADER_TOKEN(Variable, "variable")
SHADER_TOKEN(Option, "option")
SHADER_TOKEN(LayoutQualifier, "layout qualifier")
SHADER_TOKEN(InvariantQualifier, "invariant qualifier")
SHADER_TOKEN(ConstQualifier, "const qualifier")
SHADER_TOKEN(CentroidQualifier, "centroid qualifier")
SHADER_TOKEN(SampleQualifier, "sample qualifier")
SHADER_TOKEN(InQualifier, "in qualifier")
SHADER_TOKEN(OutQualifier, "out qualifier")
SHADER_TOKEN(InOutQualifier, "inout qualifier")
SHADER_TOKEN(HighpQualifier, "highp qualifier")
SHADER_TOKEN(MediumpQualifier, "mediump qualifier")
SHADER_TOKEN(LowpQualifier, "lowp qualifier")
SHADER_TOKEN(FlatQualifier, "flat qualifier")
SHADER_TOKEN(SmoothQualifier, "smooth qualifier")
SHADER_TOKEN(NoPerspectiveQualifier, "noperspective qualifier")
SHADER_TOKEN(Identifier, "identifier")
SHADER_TOKEN(BufferQualifier, "buffer qualifier")
SHADER_TOKEN(ConstantQualifier, "constant qualifier")
SHADER_TOKEN(UniformQualifier, "uniform qualifier")
SHADER_TOKEN(ResourceQualifier, "resource qualifier")
SHADER_TOKEN(StructBufferQualifier, "structbuffer qualifier")
SHADER_TOKEN(Options, "options")
SHADER_TOKEN(Error, "error")